language: php
php:
  - 7.1.9
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
services:
  - docker
before_install:
  - pip install --upgrade --no-cache-dir --default-timeout=210 skencli
script:
  - skencli
