version: 2.1
jobs:
  scan:
    machine: true
    steps:

      - checkout
      
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0

      - run:
          name: "Install"
          command: pip install --user --upgrade skencli

      - run:
          name: "Scan"
          command: skencli

workflows:
  main:
    jobs:
      - scan
