version: 2.1
jobs:
  scan:
    machine: true
    steps:

      - checkout

      - run:
          name: update pyenv
          command: |
            # Install pyenv-update to allow addition of python 3.7.0
            git clone git://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pyenv update
            pyenv install 3.6.9
      - run:
          name: Set Python Version
          command: pyenv global 3.6.9

      - run:
          name: install/update pip
          command: |
            sudo python -m pip install --upgrade pip setuptools wheel
            sudo python -m pip install --upgrade skencli

      - run:
          name: scan
          command: skencli

workflows:
  main:
    jobs:
      - scan
